### ISSUE TITLE
作者你好，请问最新的城内出行强度可以爬取吗

### ISSUE THREAD

**Issue by MOONSky1996** [samelltiger/baidu_qx#1]
作者你好，非常感谢您的分享，百度迁徙新开了一个城内出行强度的页面，这部分可以爬取吗，我没有学过爬虫，但是现在需要这部分的数据，不知道如何下手。

**Comment by samelltiger** [comment]
不好意思，最近有点忙，这个项目我现在可能顾及不过来。

**Comment by MOONSky1996** [comment]
我通过模仿你的代码已经把城内出行强度爬取下来了，您的代码对我的思路非常有帮助，非常感谢您

**Comment by samelltiger** [comment]
关闭
