### ISSUE TITLE
导入excel后显示中文乱码

### ISSUE THREAD

**Issue by wnie89** [samelltiger/baidu_qx#5]
请问我在anaconda prompt中得到的中文不是乱码，但是输出到excel里面后中文就变成乱码了。请问修改一下哪里的encoding可以解决这个问题呢？谢谢！

DEBUG: Scraped from <200 http://huiyan.baidu.com/migration/cityrank.jsonp?dt=city&id=130700&type=move_in&date=20200101>
{'city_name': '张家口市',
 'date': '20200101',
 'inOrOUt_city': '三亚市',
 'inOrout': 'move_in',
 'inOrout_city_province_name': '海南省',
 'value': 0.02}

**Comment by samelltiger** [comment]
https://jingyan.baidu.com/article/fea4511a29de73f7ba912558.html 多百度，多用Google。

**Comment by wnie89** [comment]
谢谢您！已解决。
